plateforme_produit_panier:
    resource: "@PlateformeProduitBundle/Resources/config/Panier/routing.yml"
    prefix:   /panier

plateforme_produit_produits:
    resource: "@PlateformeProduitBundle/Resources/config/Produits/routing.yml"
    prefix:   /produits

plateforme_produit_commandes:
    resource: "@PlateformeProduitBundle/Resources/config/Commandes/routing.yml"
    prefix:   /commandes

plateforme_menu_vendeur:
    resource: "@PlateformeMenuVendeurBundle/Resources/config/routing.yml"
    prefix:   /vendeur

plateforme_menu_client:
    resource: "@PlateformeMenuClientBundle/Resources/config/routing.yml"
    prefix:   /client

plateforme_user:
    resource: "@PlateformeUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login_check:
    path: /login_check

deconnexion:
    path:     /deconnexion
    defaults: { _controller: PlateformeMenuClientBundle:Menu:deconnexion }

logout:
    path:   /logout
