<?php

namespace AppBundle\Repository;

/**
 * CarnetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarnetRepository extends \Doctrine\ORM\EntityRepository
{
}
