plateforme_produit_homepage:
    path:     /
    defaults: { _controller: PlateformeProduitBundle:Default:index }


deletePanier:
    path:     /deletePanier/{pid}
    defaults: { _controller: PlateformeProduitBundle:Panier:deletePanier }

afficherPanier:
    path:     /afficherPanier
    defaults: { _controller: PlateformeProduitBundle:Panier:afficherPanier }

updatePanier:
    path:     /updatePanier/{pid}
    defaults: { _controller: PlateformeProduitBundle:Panier:updatePanier }

viderPanier:
    path:     /viderPanier
    defaults: { _controller: PlateformeProduitBundle:Panier:viderPanier }





