accueil_vendeur:
    path:     /
    defaults: { _controller: PlateformeMenuVendeurBundle:Menu:accueil }

profilvendeur:
    path:     /profil
    defaults: { _controller: PlateformeMenuVendeurBundle:Menu:accueilProfil }
