registration:
    path:     /register
    defaults: { _controller: PlateformeUserBundle:Registration:register }

login:
    path:     /
    defaults: { _controller: PlateformeUserBundle:Security:login }



showProfile:
    path:     /showProfile
    defaults: { _controller: PlateformeUserBundle:Security:showProfile }

updateProfil:
    path:     /updateProfil
    defaults: { _controller: PlateformeUserBundle:Security:updateProfil }
