home_seller:
    path:     /
    defaults: { _controller: PlateformeMenuSellerBundle:Menu:home }

home_Profile:
    path:     /profile
    defaults: { _controller: PlateformeMenuSellerBundle:Menu:home_Profile}

search_homeseller:
    path:     /search
    defaults: { _controller: PlateformeMenuSellerBundle:Menu:home_search }

searchbyTypeformseller:
    path:     /searchbyTypeform
    defaults: { _controller: PlateformeMenuSellerBundle:Menu:searchbyTypeform }

searchbyTypeseller:
    path:     /searchbyType
    defaults: { _controller: PlateformeMenuSellerBundle:Menu:searchbyType }


searchbyNameseller:
    path:     /searchbyName
    defaults: { _controller: PlateformeMenuSellerBundle:Menu:searchbyName }

searchbyNameformseller:
    path:     /searchbyNameform
    defaults: { _controller: PlateformeMenuSellerBundle:Menu:searchbyNameform }