displayProduct:
    path:     /displayProduct
    defaults: { _controller: PlateformeProductBundle:Product:displayproducts }

addProduct:
    path:     /addProduct
    defaults: { _controller: PlateformeProductBundle:Product:addProduct }

updateProduct:
    path:     /updateProducts/{prodid}
    defaults: { _controller: PlateformeProductBundle:Product:updateProducts }

deleteProduct:
    path:     /deleteProduct/{prodid}
    defaults: { _controller: PlateformeProductBundle:Product:deleteProduct }
    
emptyProduct:
    path:     /emptyProduct
    defaults: { _controller: PlateformeProductBundle:Product:emptyProduct }

addBasket:
    path:     /addBasket/{prodid}
    defaults: { _controller: PlateformeProductBundle:Product:addBasket }
